// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAybiUAOIyoTclb0XFZaS9293BRjmq3gJE',
    appId: '1:214984479622:web:b9b65ed33e3a6a75c41207',
    messagingSenderId: '214984479622',
    projectId: 'notificationapp-5d6ba',
    authDomain: 'notificationapp-5d6ba.firebaseapp.com',
    storageBucket: 'notificationapp-5d6ba.firebasestorage.app',
    measurementId: 'G-VG2JB586V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyz9ARRnp5buhJX5Kn3SEJQseydr3f3_k',
    appId: '1:214984479622:android:c44c04abb0b4c5dcc41207',
    messagingSenderId: '214984479622',
    projectId: 'notificationapp-5d6ba',
    storageBucket: 'notificationapp-5d6ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtVrlKaqZvWGW9n7ujc30z45aUZ_Ee8W0',
    appId: '1:214984479622:ios:7f74843178d82650c41207',
    messagingSenderId: '214984479622',
    projectId: 'notificationapp-5d6ba',
    storageBucket: 'notificationapp-5d6ba.firebasestorage.app',
    iosBundleId: 'com.example.notificationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtVrlKaqZvWGW9n7ujc30z45aUZ_Ee8W0',
    appId: '1:214984479622:ios:7f74843178d82650c41207',
    messagingSenderId: '214984479622',
    projectId: 'notificationapp-5d6ba',
    storageBucket: 'notificationapp-5d6ba.firebasestorage.app',
    iosBundleId: 'com.example.notificationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAybiUAOIyoTclb0XFZaS9293BRjmq3gJE',
    appId: '1:214984479622:web:6769c90abe3604dac41207',
    messagingSenderId: '214984479622',
    projectId: 'notificationapp-5d6ba',
    authDomain: 'notificationapp-5d6ba.firebaseapp.com',
    storageBucket: 'notificationapp-5d6ba.firebasestorage.app',
    measurementId: 'G-454FE9ZT1J',
  );
}
